domains:
- boho.or.kr
- blog.naver.com
- dbpia.co.kr
- facebook.com
- github.com
- humanrights.go.kr
- instagram.com
- kci.go.kr
- kisa.or.kr
- khan.co.kr
- ko.wikipedia.org
- kr.linkedin.com
- namu.wiki
- pann.nate.com
- police.go.kr
- quasarzone.com
- reddit.com
- scienceon.kisti.re.kr
- sentinelone.com
- threads.com
- tiktok.com
- twitter.com
- x.com
- youtu.be
- youtube.com
