domains:
- boho.or.kr
- blog.naver.com
- facebook.com
- github.com
- humanrights.go.kr
- instagram.com
- kisa.or.kr
- khan.co.kr
- pann.nate.com
- police.go.kr
- quasarzone.com
- twitter.com
- x.com
- youtu.be
- youtube.com
